name: Auto Approve PR from GitHub App

on:
  pull_request:
    types: [opened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'update-repository-app'
    permissions:
      pull-requests: write
    steps:
      - name: Approve Pull Request
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
