name: Auto Approve PR from GitHub App

on:
  pull_request:
    types: [opened]

jobs:
  debug-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Creator
        run: |
          echo "PR created by: ${{ github.event.pull_request.user.login }}"
          
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'yashrajdighe'
    permissions:
      pull-requests: write
    steps:
      - name: Approve Pull Request
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
